### ISSUE TITLE
Your project infringes on my company's rights

### ISSUE THREAD

**Issue by ameenross** [starters/kik#3]
Hello. I would just like to let you know, prior to suing you, that I own a company called `A` &reg;, and I noticed your excessive use of the letter `A` in your project. This is an unacceptable situation for us at A. A has decided to use all possible means of prosecution available to remove your project from GitHub, and in fact the internet at large.

Furthermore, I'd like to inform you that we have a legion of lawyers at our disposal, further referred to as our `Legal Team`. The Legal Team is already making preparations to unleash all sorts of legal measures. Please do take heed, we do not want to be a bully, so don't force us to be one!

**Comment by sobolevn** [comment]
The same story for my company called `B`. I guess your company is also somehow related to mine. My lawyers will contact you pretty soon. Both of you.

**Comment by BoudewijnvanVeen** [comment]
@ameenross Github is not the place for stupid jokes. Please put your  jokes on a more appropriate place.

**Comment by azer** [comment]
![](https://49.media.tumblr.com/085e72063ba37b97bb7180c9996e1f81/tumblr_nw2sr6399Y1uggcp9o1_r1_500.gif)

**Comment by johnstt** [comment]
**Real talk:** why not call your project kick instead of kik?
What are the odds you would start this project in **October 2015** and name it after an up-and-coming software company (_which already existed_) by chance?

This looks like the open source equivalent of patent squatting. The part in the email thread where you try to extort $30,000 out of them over this doesn't help your credibility either.

**Comment by azer** [comment]
@johnstt I never tried to extort money. Did you read the e-mails? They offered money two times;

>> Is there something we could do for you in compensation to get you to change the name?

> hahah, you’re actually being a dick. so, fuck you. don’t e-mail me back.

second time;

>> Is there nothing we can do for you that would compensate you for the hassle of changing the name?

> Yeah, you can buy it for $30.000 for the hassle of giving up with my pet project for bunch of corporate dicks

30 is just a number I made up at that point, if I wanted to extort money, I'd not talk this way.

**Comment by ameenross** [comment]
> What are the odds you would start this project in October 2015 and name it after an up-and-coming software company (which already existed) by chance?
If you ever had a class of statistics and can count to 3 to boot, pretty huge. With a company name of 3 characters, there's only 17.5k possibilities. There's at least 10 million software projects on GitHub *alone*.

By the way: https://github.com/jonschlinkert/alphabet

I rest my case...

> Honda logo for his avatar
I think this is what's called a fallacy...

I made it myself in Inkscape. Are you jealous? At least I'm not selling my cheap knockoff on ebay. But I still fail to see what my avatar has to do with Kik.


Oops, I fed the ...

**Comment by ameenross** [comment]
Oh damn I just found this! Another company that shamelessly used the 3-letter word Kik for their company! Bring out the lawyers!

http://www.kikcorp.com/

**Comment by ciruz** [comment]
Kik will always be this company for me: https://en.m.wikipedia.org/wiki/KiK

**Comment by dannguyen** [comment]
I don't understand the trademark argument. @azer's kik project wasn't a chat client, was it? He wasn't using "kik" in a way to generically describe what Kik does...so this doesn't seem to be like the situation in which Xerox lost trademark because of the way people use the phrase "xerox" to generically mean "photocopy"

https://en.wikipedia.org/wiki/Generic_trademark

> A trademark is said to become genericized when it began as a distinctive product identifier but has changed in meaning to become generic. This typically happens when the products or services with which the trademark is associated have acquired substantial market dominance or mind share, such that the primary meaning of the genericized trademark becomes the product or service itself rather than an indication of source for the product or service.

**Comment by adnanh** [comment]
And the fact that on qwerty keyboard kik is lol offset by 1 char to the left. Do we infringe their trademark when we make such typo?

**Comment by tjmonsi** [comment]
Just a nobody here... but it's funny how media is spinning this up:
- [How one developer just broke Node, Babel and thousands of... ](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/)
- [Annoyed Developer Brings Down Thousands of Javascript & Node.js Projects](http://news.softpedia.com/news/annoyed-developer-brings-down-thousands-of-javascript-node-js-projects-502075.shtml)
- [Disgruntled developer breaks thousands of Javascript, Node.js, apps](http://www.zdnet.com/article/disgruntled-developer-breaks-thousands-of-javascript-node-js-apps/)
- [One angry programmer almost broke the Internet by deleting eleven lines of code](http://www.businessinsider.com/npm-left-pad-controversy-explained-2016-3)


From just one developer, to being annoyed, then disgruntled, then angry...

Going back, I find it really weird that they just gave you the "I'm not a dick, but lawyers will be banging at your door" move (clearly a threat)... (I read the email conversations [here](https://medium.com/@mproberts/a-discussion-about-the-breaking-of-the-internet-3d4d2a83aa4d)), what's 'more weird' is that they already have 'kik-lib' registered in npm... (and then wanted to change it to 'kik' I guess)

If they pulled out the trademark issue here, they should have also pulled it out to other companies using the word kik. (someone showed a http://kikcorp.com and http://kik.de)

This is clearly bullying now because you are just a lone developer... and though you have broken a lot (maybe topping up Kim Kardashian's breaking the Internet IRL and not just her butt), I believe you have made a point here and I salute you.

**Comment by johnstt** [comment]
Is the point made that it's not smart to build tons of infrastructure on top of projects owned by people who throw tantrums over stuff that doesn't matter?

**Comment by XaeroDegreaz** [comment]
I just find it hilarious how brittle the Node ecosystem is. Is there no concept of caching dependencies in a repository like Nexus for Maven artifacts? Once they are retrieved you'd just pull them from your local cache repo or from a remote repo that you control.

**Comment by hannakfoo** [comment]
I suggest you register "kik-lib" asap as a trademark, rename this repo .. and claim your kik-lib ..

https://www.npmjs.com/package/kik-lib

Kik API - NodeJS Library
For any webapp, some features will require having a backend. This NodeJS package makes verifying user

**Comment by ameenross** [comment]
@johnstt So instead of making snarky remarks, which clearly show you didn't change opinion, how about an actual rebuttal of the various arguments? Or even just a new argument from your position?

**Comment by armw4** [comment]
I salute you sir. For refusing to back down .

**Comment by johnstt** [comment]
He took his project off npm. I think that counts as backing down.

**Comment by azer** [comment]
@johnstt what would you recommend ?

**Comment by johnstt** [comment]
Okay but you wrote [here](https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.jztvjj66o) that you had 'unpublished all [your] modules'. You also asked them to delete your modules and account [over here](https://medium.com/@mproberts/a-discussion-about-the-breaking-of-the-internet-3d4d2a83aa4d#.4zvs6h9yu).

The only part where you 'made a stand' or whatever people are claiming is when you childishly said "fuck you" to them in the email threads. The rest of the story is you taking your stuff down in a panic and then trying to spin it as anti-corporate heroics.

**Comment by armw4** [comment]
False

**Comment by armw4** [comment]
This guy is a hero based on *my* standards.

**Comment by bravedick** [comment]
kik is dick 8====================================================================================================D~~~~~~~~~~~~~

**Comment by tjmonsi** [comment]
@johnstt well here's the thing that i understand about this issue. If npm
would just forceably change a registered name in the registry just because
there is a threat (not even a legitimate order from court) just because of
"trademark" issues (that isn't even the case here), then there's really a
big problem with corporate (or even startups) calling in their trademark
lawyers, taking in npm registered modules, threatening independent open
source devs because they know they can be be pushed over, and then those
projects who are dependent on a registered module that was taken over
become broken because of this move by npm.

It's a good thing that the company was called kik. But what if it was
left-pad? And then that company tried to threaten @azer for using left-pad
trademark because they want to use left-pad as a registered module? And
then npm agreed without a court-order to change left-pad ownership from
@azer to the left-pad company. That would inevitibly just broke the node js
part of the internet in itself. In this sense, it would be the same.

I would agree that both parties could have resolved this matter in a more
professional way (without the fuck you and dick move). Like for one, @azer
could have been professional in the whole exchange by not using swear words
but still sticking up to his guns (but i understand when kik pulled up its
trademark threat card aka the dick move, at this point kik was not
professional al ready). Another is kik already has kik-lib registered. this
could have been averted if kik already registered kik since 2013-2014
(@azer only registered kik i think at about 2015 based on git repo
creation). Another is if devs are already using kik-lib, then they would be
doing a disservice to those devs by changing fron kik-lib to kik just for
node (and then just making kik-iphone and kik-android the same), they could
just use kik-js to retain consistency. In any case, if they pulled the
trademark card on this, why only on @azer, why not use it on kikcorp.com
and kik.de as well? Clearly the dick move email on lawyers banging at your
door is a corporate blackmail of threat of some sort.

but given the situation now, whining that @azer is doing a tantrum is
short-sighted and would be just like someone throwing another tantrum
because his/her own project isn't working and just blaming @azer without
knowing the bigger issue at hand.

Just my 2 cents.

**Comment by kflorence** [comment]
lol the internet

**Comment by johnstt** [comment]
>Another is kik already has kik-lib registered. this
could have been averted if kik already registered kik since 2013-2014
(@azer only registered kik i think at about 2015 based on git repo
creation). 

Exactly! Kik already existed (as a company that gets namedropped frequently) when Azer created his project. That's why I said it's like patent squatting - if I make an npm package called microsoft right now and then sit and wait for them to react, what I'm doing is in really bad faith. When I pointed out how unlikely it would be to pick 'kik' as the name purely by accident (with zero awareness of the software startup) the best you guys could do was say "it's like typing lol and moving over 1 key!", or this weird line about "_statistics_"?

>If you ever had a class of statistics and can count to 3 to boot, pretty huge. With a company name of 3 characters, there's only 17.5k possibilities. There's at least 10 million software projects on GitHub alone.

**Comment by tjmonsi** [comment]
I would really never know if it is really done to name squat or pure
coincidence (as azer also has kik-starter repo aside from kik). As far as i
know, i don't know kik exists until now (but i am way over on the other
side of the globe and we know viber and whatsapp) I understand your point
of view though, @azer could have just move it... But there might be
packages that are already dependent on kik (that we have to check) which
would be broken if npm just forceably changed its registry... Although it
might be very likely also for me (at least for me) to use kik because it is
a play of words for kick... And then kickstarter to kik-starter...

Trademark-wise though, what ive read so far is that having kik registered
in npm is not covered in trademark, if it was... They could have called
every registered 'kik' name not only in npm, but also in github, bitbucket,
gitlab and other sites like kikcorp and kik.de because they have the same
name on the clause that 'consumers/developers might be confused'...

But nevertheless this happened and now we just opened a big can of worms...

- npm can be sent an email and even without a court order can also force
another person to change the module's ownership to another person (just
because the requestor has some threat up its sleeve called lawyers, and the
other is just a dev)
- the ability to break other people's code by removing modules in npm
- the instance of a first-come-first-served basis of registering modules at
npm (they could have been a global company name registration if this would
be the case)
- the ability for other people to take ownership of a removed module and
can put malicious code in it

**Comment by tjmonsi** [comment]
Here's what joepie91's take from http://cryto.net/~joepie91/blog/2016/03/23/reflections-on-npm-gate-one-day-later/ that is really bothering me on this issue:

> ## NPM Inc.'s response

> NPM Inc. removed Azer's package without any real infringement claim ever having been sent, purely on the basis of the threat of getting lawyers involved.
> 
> By doing this, NPM Inc. has painted a giant target on their back towards trademark trolls, saying "here's a cheap target" - it is now known that they will not make an effort to represent the interests of their users, and will fold even without a legal notice being sent.
> 
> This is disastrous for the ecosystem, as every developer is now a potential target, and their package might be pulled out from under their feet as well, for an entirely frivolous claim.

And this one...

> ## But Azer could have published malware as well.

> Yes, he could have. But he was the only person who could modify his packages (aside from NPM Inc. itself), and people decided to trust him as a legitimate developer. That trust breaks down when you quietly **'reallocate'** a package to a different, entirely unrelated person.
> 
> Signed packages would be even better, of course - but even without that, preventing reallocation of package names is the most basic protection you should really have.

I think, for me, that is a bigger issue than kik holding a trademark and being the 'first'...

**Comment by ameenross** [comment]
> this weird line about "statistics"?

So still no arguments. Just calling an argument "silly" is not going to magically invalidate it. I'm going to say *yawn*

> It might be believable that this was all some really unlikely accident, if there wasn't also a thread sitting here with you guys childishly mocking the Kik request

Disclaimer: I am not affiliated and have no dealings with @azer, I don't know him, and in fact I never knew about his existence until I read about it in online media. Feel free to see a conspiracy here... I'll just be here laughing at you.

**Comment by waynebloss** [comment]
"Someone took my made-up name! I don't like following laws! Waaaaah"

LOL

Everybody in this little drama came off looking like a whiny ass bitch. Congrats!

**Comment by Coreinsanity** [comment]
This entire thing seems stupid and childish. So, from everything I have to go off of, they politely ask you to rename the library because they want to develop modules for their product using their trademarked name. Seems perfectly understandable to me. You could have just worked with them, asking NPM to work with you, renaming your library, and then maybe get them to link to the new one so your users could find it and not get confused. Instead you replied like a total immature ass, and then proceed to take down everything off NPM because (understandably) they aren't going to get into some legal crap over the name of two libraries and took the ones in question down. And then you try to play it off as some kind of anti-corporation heroism BS.

**Comment by ameenross** [comment]
Your resume says nothing about trademark law (or even law in general). How do you happen to be so certain that trademark law agrees with Kik Messenger having the exclusive right to register a package with the name Kik on npm.org? Others, with at least *some* experience with trademark, have written and pointed out that it isn't so self-evident as you and others seem to think.

Anyways... I noticed this: https://github.com/waynebloss/wurli
 
And this: https://trademarks.justia.com/775/11/wurli-worm-77511368.html

Hmmm, do you see the potential there? Anyway this issue is starting to invite folks from 4chan or something, so I won't stay here for much longer :sweat_smile:

**Comment by waynebloss** [comment]
The best thing about this whole thing is that NPM Inc. will now make it harder for you to be this childish in the future because ["We will make it harder to un-publish a version of a package if doing so would break other packages."](http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm).

Good. Thanks for your code tho ;)

**Comment by waynebloss** [comment]
@ameenross If someone from WURLI corp. asked me to un-publish it, I certainly wouldn't act like a fucking cry baby though.

But I'm really glad somebody did, because now they won't be able to do that in the future thanks to NPM's reaction. So, either way I win.

**Comment by ameenross** [comment]
> either way I we all win

This is something my 5-year-old could have said. But really, if they'd file suit and win, you don't win. Unless you're a masochist.

> so it appears that you know even less than I do because Games and playthings are not software.

No? So, sorry all you 'puter gamers out there! Games are not software. Period.

**Comment by waynebloss** [comment]
> This is something my 5-year-old could have said.

Is it? I'd like to see that. In any case, you don't really win anything by saying "This is something my 5-year-old could have said". I could say that about your entire stance here. It's *almost* as childish as Azer's reaction. *Almost*.

> No? So, sorry all you 'puter gamers out there! Games are not software. Period.

You're not making any sense.

**Comment by johnstt** [comment]
Guys watch out the javascript one-liner developers are going to hunt down your resumes and cherrypick things to grill you on

**Comment by ameenross** [comment]
> You're not making any sense.

Well I'm just kinda paraphrasing you so... You basically said "Fruit is not an apple". That doesn't make any sense at all. If you have a fruit, it *could* be an apple. You know, apple being a descendant of fruit and all? Now about games, they could be software. Software is not a single landscape of nearly identical things either. So if I am a software company making embedded systems I don't think I would be considered as "in the same industry" as a company specializing in webapps. The situation with Kik messenger and the original Kik project is the same. Completely different things.

And there was no *polite* offer here, unless you consider threatening with lawyers polite. And I wouldn't wanna be your friend if you think threatening is friendly. Also, it's extremely common for CLI tools to have the shortest possible names so typing them is fast, `kik` is a perfect choice in that regard.

Anyways I'm done here, what started out as a lighthearted joke is starting to become a place for trolling.

**Comment by johnstt** [comment]
@ameenross  : I tried to find your resume so I could make fun of you, but your website seems to just be a forum login screen from 1997? Get at me with some details :^}

**Comment by waynebloss** [comment]
> Completely different things.

So now you're a lawyer? OK

Thanks for all the laughs!

**Comment by ameenross** [comment]
I'll unsubscribe before posting. This thread is all yours

> So now you're a lawyer? OK

Sorry I forgot to type the regular disclaimers: IANAL, YMMV
I was just stating my opinion that I think that an IM network is something different than a CLI tool to aid Node developers

**Comment by waynebloss** [comment]
> I'll unsubscribe before posting.

This is the Internet equivalent of "Nah Nah Nah, I HAVE MY FINGERS IN MY EARS AND I CAN'T HEAR YOU!".

I can definitely see why you're siding with a guy who throws hissy fits because he lost an argument about a made-up name that could have easily been changed.

**Comment by azer** [comment]
@johnstt @waynebloss I'm not hesitating to be hated by everyone in the industry, especially the assholes like you two. Keep kissing corporate ass, just get the fuck out from my head.

**Comment by waynebloss** [comment]
@azer I am most certainly an asshole, just like you but, but, but...We don't hate you! I don't at least... :) Lots of folks do childish things that hurt totally innocent people, but it's important that they know it when all is said and done.

You did a really selfish thing. Probably without thinking much about it. That's the way it seems to me at least. It's totally OK if you're a nice guy about it, but you weren't and you're not.

Not sure if you heard the part where I said that I thought *both sides* looked really bad in this though. So I don't see how I'm a "corporate asshole". Just a regular one! Thanks.

**Comment by waynebloss** [comment]
It's basically your *opinion* that you should be able to *publish* a work under the word "kik" on NPM and you did everything in your power to keep it, right?

Well, why shouldn't someone of a different opinion do everything in *their power* to do things the way they want to?

That's where laws and lawyers come in and that's just the way things are. What are you going to do? Bring down the government? No. Go get your own lawyers if you feel so strongly about it. Where's your legal fund?
